### ISSUE TITLE
Registering Commands

### ISSUE THREAD

**Issue by R-Haecker** [metallkopf/konnect#3]
How can I register a command for the KDE-Connect app.
Instead of using the system settings GUI i.e. [here](https://userbase.kde.org/KDE_Connect/Tutorials/Adding_commands).
I didn't find a way how to do this in the current version of konnect.

Is there a directory where one could define files to register commands such as shell scripts or .desktop files (for example in home/user/.config/konnect/commands/your_command.desktop) to register them for use in the client app.

Thanks for any input.

**Comment by metallkopf** [comment]
You can't, i haven't implemented support for that, but am working on it.

**Comment by serious-angel** [comment]
I am sorry, but to clarify, is it possible to use the interesting solution to control input like mouse/keyboard, considering pairing?

**Comment by ferdiu** [comment]
> You can't, i haven't implemented support for that, but am working on it.

Hi, I am really interested in this project.

You said you are working on this feature but I do not see any branch named after this (actually no branch at all apart from master). If you have a local branch do you mind pushing it to this remote to share?
I am willing to help in the process of this implementation since I need it for a project but I do not want to waste time doing it from scratch if you have some work already done here.

PS If you have any preliminary work on design and documentation they would certainly help.

**Comment by metallkopf** [comment]
> I am sorry, but to clarify, is it possible to use the interesting solution to control input like mouse/keyboard, considering pairing?

that is something totally different from what the OP is asking, and you should create another issue explaining your use case.

**Comment by metallkopf** [comment]
@R-Haecker and @ferdiu you should checkout release 0.2.0.

**Comment by ferdiu** [comment]
Wow that was quick :smiley: . I will definitely do. Thanks a lot.

**Comment by metallkopf** [comment]
> Wow that was quick 😃 . I will definitely do. Thanks a lot.

no, it wasn't, i started working on it a couple of weeks ago.

**Comment by R-Haecker** [comment]
Thank you for this project and this additional feature. Very much appreciated.

I have one more question, I am not sure if it fits this issue or if I should post this somewhere else.

Can I execute a remote command on the system that is running Konnect itself?

I would like to execute a command on the headless machine running Konnect. With the new implementation I can register commands by specifying another device running KDE connect and execute the command on these devices (I hope I understood this is correctly). I would like to have the option to use the device running the Konnect service to be able to execute commands itself. Is that somehow possible to have a "device" option which represents the same device running Konnect and assigning commands to it?

Thanks for any input and please tell me if this question should be moved to another issue.

**Comment by metallkopf** [comment]
yes, add a command for that device on konnect and you can execute it remotely from the kde-connect[-android] gui

**Comment by metallkopf** [comment]
you can only execute commands from or to a paired device
